### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by UWPA** [Extremelyd1/Strat-Roulette#29] opened 2019-07-16 21:33 UTC
**Describe the bug**
The server will just crash
**To Reproduce**
I have no idea, just playing and it crashed.

**Expected behavior**
When playing, sometimes it just crashes. Sometimes lasts 3-4 rounds, sometimes doesn't even last a round.

**Comment by Extremelyd1** [comment] 2019-08-08 12:16
Please provide a crash log/report or a way to replicate the issue. Otherwise I can't fix this.

**Comment by 0xGabrielel** [comment] 2019-08-08 16:49
I also encountered some random crashes.

Nothing can be seen in the logs as the console just gives a segmentation fault error.

However, I installed Throttle and let it find the issue of the crash: https://crash.limetech.org/to5rabzuw4vo

It looks like there is something that makes the server crash in the handling of the round veto menu.

In order to reproduce the issue, you need at least 2 active real players (not 1 player and 1 bot), and one of them should not vote when the veto appears. 
This triggers the crash (at least for me).

**Comment by Extremelyd1** [comment] 2019-08-08 19:49
The segmentation fault is possibly fixed now, if someone is kind enough to verify this I can close the issue. Unfortunately, I can't seem to replicate the issue locally.

**Comment by 0xGabrielel** [comment] 2019-08-08 21:05
It looks like it's fixed now

**Closed as completed** 2019-08-08 22:16 UTC
Labels: bug
